<?php

namespace CD\LouvreBundle\Repository;


/**
 * PurchaseOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseOrderRepository extends \Doctrine\ORM\EntityRepository
{
	public function placesPerDay($date)
	{
		$query = $this->createQueryBuilder('q')
			->select('SUM(q.numberTicketsDesired)')
			->where('q.visitDate = :date')
			->andWhere('q.orderValidation = 1')
			->setParameter('date', $date)
			->getQuery()
			->getSingleScalarResult()
		;
		return $query;
	}

	// sélectionne le nombre de commande validé par date de visite
	public function fullDay()
	{
		$query = $this->createQueryBuilder('q')
			->select('q.visitDate', 'SUM(q.numberTicketsDesired) as Places')
			->where('q.orderValidation = 1')
			->groupBy('q.visitDate')
			->getQuery()
			->getScalarResult()
		;
		return $query;
	}

}
