<?php

namespace CD\LouvreBundle\Repository;


/**
 * PurchaseOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseOrderRepository extends \Doctrine\ORM\EntityRepository
{
	// Sélectionne le nombre de place commandé pour un jour donné et retourne ce nombre.
	/**
	 * @param $date
	 * @return mixed
	 * @throws \Doctrine\ORM\NoResultException
	 * @throws \Doctrine\ORM\NonUniqueResultException
	 */
	public function placesPerDay($date)
	{
		$query = $this->createQueryBuilder('q')
			->select('SUM(q.numberTicketsDesired)')
			->where('q.visitDate = :date')
			->andWhere('q.orderValidation = 1')
			->setParameter('date', $date)
			->getQuery()
			->getSingleScalarResult()
		;
		return $query;
	}

	// sélectionne le nombre de commande validé par date de visite et retourne le nombre de commande pour chaque date de
	// visite.
	public function fullDay()
	{
		$query = $this->createQueryBuilder('q')
			->select('q.visitDate', 'SUM(q.numberTicketsDesired) as Places')
			->where('q.orderValidation = 1')
			->groupBy('q.visitDate')
			->getQuery()
			->getScalarResult()
		;
		return $query;
	}

}
