<?php

namespace CD\LouvreBundle\Repository;

/**
 * TicketDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
