cd_louvre:
    resource: "@CDLouvreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
#******************** Route HomeController *****************************************************************#

cd_louvre_home:
    path:     /
    defaults: { _controller: CDLouvreBundle:Home:home }