#cd_louvre_homepage:
 #   path:     /
 #   defaults: { _controller: CDLouvreBundle:Default:index }

#******************** Route HomeController *****************************************************************#

louvre_home:
    path:     /
    defaults: { _controller: CDLouvreBundle:Home:home }

#******************** Route controller RecoveryDisponibilityController **********************************
louvre_recovery_disponibilityDay:
    path:     /disponibilityDay
    defaults: { _controller: CDLouvreBundle:RecoveryDisponibility:disponibilityDay }
louvre_recovery_numberPlaces:
    path:     /numberPlaces/{dateTab}
    defaults: { _controller: CDLouvreBundle:RecoveryDisponibility:numberPlaces }

#******************* Route controller OrderDescriptionController***********************************************
cd_louvre_description:
    path:    /description
    defaults: {_controller: CDLouvreBundle:OrderDescription:description }
    requirements:
        id: \d+
