services:
#    cd_louvre.example:
#        class: CD\LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    cd_louvre.services.cdorder_handling:
        class: CD\LouvreBundle\Services\CDOrderHandling
        arguments: ["@doctrine.orm.entity_manager",maxPlacesPerDay]